//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestStrežnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Izguba
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public decimal StandardCost { get; set; }
        public decimal ListPrice { get; set; }
        public Nullable<decimal> AvgSellingPrice { get; set; }
    }
}
